format = """
[ ó°‰‹]( fg:#33dd2d bg:#2E2F38)\
$directory\
$git_branch\
$git_status\
$bun\ 
[ |](fg:#ED333B bg:#2E2F38)\
[ ]()\

"""
# [ :: ](fg:#ED333B bg:#2E2F38)\
# ã€¢ â”†  â±
right_format = """
$bun\
$nodejs\
"""


[fill]
symbol=" "
[line_break]
disabled = false

####### Sections
[directory]
style = "fg:#33dd2d bg:#2E2F38"
format = "[ $path ]($style)"


truncation_length =0
truncation_symbol = "~/"



[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "



[git_branch]
symbol = "ï˜ "
style = "fg:#e5e512 bg:#242424"

format = "[ $symbol$branch(:$remote_branch) ]($style)"



[git_commit]

commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_status]
# disabled = true
style = "fg:#e5e512 bg:#242424"
staged = "ï€Œ ${count}" # nf-fa-check
modified = " ï„ ${count}" # nf-fa-edit
# modified = " ï€ ${count}" # nf-fa-pencil
renamed = "ó°—§${count}" # nf-md-cursor_text
untracked = " U${count}" # nf-fa-question
deleted = " ï€ ${count}" # nf-fa-remove
conflicted = "ï€¤${count}" # nf-fa-flag
stashed = " ï†œ ${count}" # nf-fa-bank
# stashed = " ï€œ ${count}" # nf-fa-inbox
up_to_date = ""
ahead = "ó°™ ${count}" # nf-md-arrow_expand_up
behind = "ó°– ${count}" # nf-md-arrow_expand_down
diverged = "ó°¡ ${ahead_count} ${behind_count}" # nf-md-arrow_expand_vertical
# diverged = "ó°¯ ${ahead_count} ${behind_count}" # nf-md-swap_vertical_bold
# ignore_submodules = true
format = "[($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind )]($style)"

[git_state]
# disabled = true
style = "bg:color_git_state fg:color_foreground_dark"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "îŠ› picking" # nf-fae-cherry
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '[$state($progress_current/$progress_total)]($style)'

[git_metrics]
disabled = false
added_style = 'bg:color_git_metrics fg:color_foreground_light'
deleted_style = 'bg:color_git_metrics fg:color_foreground_light'
# only_nonzero_diffs = false
# format = '([ó°ºª $added]($added_style))([ ó°º¨ $deleted]($deleted_style))' # ó°ºª = nf-md-text_box_plus // ó°º¨ = nf-md-text_box_minus
format = '([ó°ºª ](bg:color_git_metrics fg:color_git_metrics_added)[$added]($added_style))([ ó°º¨ ](bg:color_git_metrics fg:color_git_metrics_deleted)[$deleted]($deleted_style))' # ó°ºª = nf-md-text_box_plus // ó°º¨ = nf-md-text_box_minus




[bun]
# disabled = true
symbol = "bun" # nf-oct-smiley
style = "bg:color_toolchain fg:color_toolchain_text"
detect_files = ['bun.lockb', 'bunfig.toml']
format = "[[#](fg:#739aa1 bg:#2E2F38)[BUN ](red bg:#2E2F38)($version)](red bg:#2E2F38)[# ](fg:#739aa1 bg:#2E2F38)"

[nodejs]
# disabled = true
symbol = "ó°™ " # nf-md-nodejs
style = "bg:color_toolchain fg:color_toolchain_text"
not_capable_style = "bg:color_toolchain fg:color_foreground_dark"
format = "[$symbol($version)]($style)"
